// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybwoinucidnpciyndpyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlid29pbnVjaWRucGNpeW5kcHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDU1OTMsImV4cCI6MjA3MDUyMTU5M30.BhljckVZvPfEuTFkCwMVBVKSBiiM5WZAN0RGpyk4SYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});